# fly.toml app configuration file generated for bun-quickstart on 2024-02-18T13:59:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bun-quickstart'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
